import type { User } from "./user"

export const users: User[] = [
  {
    id: 1,
    name: "Davis Curtis",
    avatar: "/avatars/davis.png",
    flag: "/flags/pt.png",
    points: 2569,
  },
  {
    id: 2,
    name: "Alena Donin",
    avatar: "/avatars/alena.png",
    flag: "/flags/fr.png",
    points: 1469,
  },
  {
    id: 3,
    name: "Craig Gouse",
    avatar: "/avatars/craig.png",
    flag: "/flags/ca.png",
    points: 1053,
  },
  {
    id: 4,
    name: "Madelyn Dias",
    avatar: "/avatars/madelyn.png",
    flag: "/flags/hu.png",
    points: 590,
  },
  {
    id: 5,
    name: "Zain Vaccaro",
    avatar: "/avatars/zain.png",
    flag: "/flags/it.png",
    points: 448,
  },
  {
    id: 6,
    name: "Skylar Geidt",
    avatar: "/avatars/skylar.png",
    flag: "/flags/ru.png",
    points: 448,
  },
  {
    id: 7,
    name: "Justin Bator",
    avatar: "/avatars/justin.png",
    flag: "/flags/no.png",
    points: 448,
  },
  {
    id: 8,
    name: "Cooper Lipshutz",
    avatar: "/avatars/cooper.png",
    flag: "/flags/de.png",
    points: 448,
  },
  {
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },
  {
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },{
    id: 9,
    name: "Alfredo Septimus",
    avatar: "/avatars/alfredo.png",
    flag: "/flags/es.png",
    points: 448,
  },
]

