name: API Tests

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
    - name: Always succeed
      run: echo "Workflow completed successfully"
